### ISSUE TITLE
Recognize Lua

### ISSUE THREAD

**Issue by hyperrealgopher** [hyperreal-gopher/filesig#4]
Lua bytecode (.luac): "\x1BLua"

**Comment by Erutuon** [comment]
Can also distinguish version numbers, for versions 3.1 and above, if you want, using the two nibbles after `"\x1BLua"`; for instance, `"\x1BLua\x53"` signifies Lua 5.3 bytecode. (I checked 3.0 to 5.0 to make sure, but couldn't get 2.5 to compile. 3.0 had "\x25", the previous version number apparently, where it should have "\x30".)

Probably the earlier versions are not much used (see the [full list](https://www.lua.org/versions.html)). So you could define separate signatures for, say, versions 4.0 and above rather than parsing the nibbles.
